import 'mock_models.dart';

final List<MockLabTest> mockLabTests = [
  const MockLabTest(
    id: '1',
    name: 'CBC',
    slug: 'cbc',
    includes: [
      'Hemoglobin',
      'WBC Count',
      'Platelet Count',
      'RBC Count',
      'Hematocrit',
    ],
    mrp: 500,
    salePrice: 375,
    discountPercent: 25,
    reportHours: 24,
    preparation: 'No fasting required. Can be done any time.',
    imageUrl: '',
  ),
  const MockLabTest(
    id: '2',
    name: 'Dengue Package',
    slug: 'dengue-package',
    includes: ['NS1 Antigen', 'CBC', 'IgG Antibody', 'IgM Antibody'],
    mrp: 1800,
    salePrice: 1350,
    discountPercent: 25,
    reportHours: 6,
    preparation: 'No special preparation needed.',
    imageUrl: '',
  ),
  const MockLabTest(
    id: '3',
    name: 'Thyroid Profile',
    slug: 'thyroid-profile',
    includes: ['T3', 'T4', 'TSH'],
    mrp: 1200,
    salePrice: 900,
    discountPercent: 25,
    reportHours: 24,
    preparation: '8 hours fasting required. Morning sample preferred.',
    imageUrl: '',
  ),
  const MockLabTest(
    id: '4',
    name: 'Blood Sugar',
    slug: 'blood-sugar',
    includes: ['Fasting Blood Glucose', 'Post-Prandial Blood Glucose'],
    mrp: 400,
    salePrice: 300,
    discountPercent: 25,
    reportHours: 4,
    preparation: '8-12 hours fasting before first sample.',
    imageUrl: '',
  ),
  const MockLabTest(
    id: '5',
    name: 'Lipid Profile',
    slug: 'lipid-profile',
    includes: ['Total Cholesterol', 'LDL', 'HDL', 'Triglycerides', 'VLDL'],
    mrp: 800,
    salePrice: 600,
    discountPercent: 25,
    reportHours: 24,
    preparation: '12 hours fasting required.',
    imageUrl: '',
  ),
];
