import 'mock_models.dart';

const _defaultDesc =
    'HealMeal brings authentic medicines and healthcare essentials from trusted Bangladeshi sources with safe delivery and pharmacist support.';
const _defaultUse = 'Take or use as directed by your healthcare professional.';
const _defaultEffects =
    'If discomfort occurs, stop using and consult a doctor.';
const _defaultStorage = 'Store in a cool, dry place away from direct sunlight.';

final List<MockProduct> mockMedicines = [
  const MockProduct(
    id: '1',
    name: 'Napa Extra 500mg Tablet (10s)',
    slug: 'napa-extra-500mg-tablet-10s',
    brandName: 'Beximco Pharma',
    categorySlug: 'medicines',
    mrp: 20,
    salePrice: 16,
    discountPercent: 20,
    reviewCount: 128,
    rating: 4.5,
    isRxRequired: false,
    isFlashSale: false,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 2,
    stockLeft: 18,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '2',
    name: 'Accu-Chek Active',
    slug: 'accu-chek-active',
    brandName: 'Roche',
    categorySlug: 'healthcare',
    mrp: 1500,
    salePrice: 500,
    discountPercent: 67,
    reviewCount: 52,
    rating: 4.3,
    isRxRequired: false,
    isFlashSale: true,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 25,
    stockLeft: 9,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '3',
    name: 'Insulin Mixtard',
    slug: 'insulin-mixtard',
    brandName: 'Novo Nordisk',
    categorySlug: 'medicines',
    mrp: 450,
    salePrice: 405,
    discountPercent: 10,
    reviewCount: 203,
    rating: 4.8,
    isRxRequired: true,
    isFlashSale: false,
    inStock: false,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 12,
    stockLeft: 0,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '4',
    name: 'Seclo 20mg',
    slug: 'seclo-20mg',
    brandName: 'Square Pharma',
    categorySlug: 'medicines',
    mrp: 98,
    salePrice: 82,
    discountPercent: 16,
    reviewCount: 76,
    rating: 4.4,
    isRxRequired: false,
    isFlashSale: true,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 4,
    stockLeft: 6,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '5',
    name: 'Monas 10',
    slug: 'monas-10',
    brandName: 'ACI',
    categorySlug: 'medicines',
    mrp: 160,
    salePrice: 144,
    discountPercent: 10,
    reviewCount: 64,
    rating: 4.2,
    isRxRequired: false,
    isFlashSale: false,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 5,
    stockLeft: 11,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '6',
    name: 'Amdocal 5',
    slug: 'amdocal-5',
    brandName: 'Incepta',
    categorySlug: 'cardiac-care',
    mrp: 360,
    salePrice: 310,
    discountPercent: 14,
    reviewCount: 40,
    rating: 4.6,
    isRxRequired: true,
    isFlashSale: false,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 8,
    stockLeft: 4,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '7',
    name: 'Nervalin',
    slug: 'nervalin-75',
    brandName: 'Drug International',
    categorySlug: 'medicines',
    mrp: 220,
    salePrice: 187,
    discountPercent: 15,
    reviewCount: 34,
    rating: 4.3,
    isRxRequired: true,
    isFlashSale: false,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 6,
    stockLeft: 7,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '8',
    name: 'Orsaline-N',
    slug: 'orsaline-n',
    brandName: 'Square',
    categorySlug: 'healthcare',
    mrp: 30,
    salePrice: 25,
    discountPercent: 17,
    reviewCount: 29,
    rating: 4.7,
    isRxRequired: false,
    isFlashSale: true,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 1,
    stockLeft: 22,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '9',
    name: 'Ceevit Vitamin',
    slug: 'ceevit-vitamin',
    brandName: 'Square',
    categorySlug: 'supplement',
    mrp: 120,
    salePrice: 96,
    discountPercent: 20,
    reviewCount: 57,
    rating: 4.5,
    isRxRequired: false,
    isFlashSale: true,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 4,
    stockLeft: 13,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '10',
    name: 'NeoCare BP',
    slug: 'neocare-bp',
    brandName: 'NeoCare',
    categorySlug: 'healthcare',
    mrp: 2450,
    salePrice: 1980,
    discountPercent: 19,
    reviewCount: 21,
    rating: 4.4,
    isRxRequired: false,
    isFlashSale: false,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '24 HRS',
    cashback: 35,
    stockLeft: 5,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '11',
    name: 'Nebulizer',
    slug: 'nebulizer',
    brandName: 'Omron',
    categorySlug: 'healthcare',
    mrp: 4200,
    salePrice: 3490,
    discountPercent: 17,
    reviewCount: 18,
    rating: 4.8,
    isRxRequired: false,
    isFlashSale: false,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '24 HRS',
    cashback: 52,
    stockLeft: 3,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '12',
    name: 'Visine Eye Drops',
    slug: 'visine-eye-drops',
    brandName: 'Pfizer',
    categorySlug: 'healthcare',
    mrp: 180,
    salePrice: 162,
    discountPercent: 10,
    reviewCount: 31,
    rating: 4.1,
    isRxRequired: false,
    isFlashSale: false,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 5,
    stockLeft: 10,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '13',
    name: 'Sensodyne Repair',
    slug: 'sensodyne-repair',
    brandName: 'GSK',
    categorySlug: 'healthcare',
    mrp: 260,
    salePrice: 210,
    discountPercent: 19,
    reviewCount: 44,
    rating: 4.5,
    isRxRequired: false,
    isFlashSale: true,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 6,
    stockLeft: 8,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '14',
    name: 'OneTouch Test',
    slug: 'onetouch-test',
    brandName: 'LifeScan',
    categorySlug: 'diabetic-care',
    mrp: 1100,
    salePrice: 980,
    discountPercent: 11,
    reviewCount: 22,
    rating: 4.6,
    isRxRequired: false,
    isFlashSale: false,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '24 HRS',
    cashback: 18,
    stockLeft: 4,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '15',
    name: 'Pulse Oximeter',
    slug: 'pulse-oximeter',
    brandName: 'Yuwell',
    categorySlug: 'healthcare',
    mrp: 1400,
    salePrice: 999,
    discountPercent: 29,
    reviewCount: 64,
    rating: 4.7,
    isRxRequired: false,
    isFlashSale: true,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '24 HRS',
    cashback: 20,
    stockLeft: 7,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '16',
    name: 'Surgical Mask',
    slug: 'surgical-mask',
    brandName: '3A Healthcare',
    categorySlug: 'healthcare',
    mrp: 250,
    salePrice: 175,
    discountPercent: 30,
    reviewCount: 88,
    rating: 4.3,
    isRxRequired: false,
    isFlashSale: true,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 4,
    stockLeft: 30,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '17',
    name: 'Pregnancy Test',
    slug: 'pregnancy-test',
    brandName: 'MediTest',
    categorySlug: 'baby-mom-care',
    mrp: 80,
    salePrice: 60,
    discountPercent: 25,
    reviewCount: 26,
    rating: 4.2,
    isRxRequired: false,
    isFlashSale: false,
    inStock: false,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 2,
    stockLeft: 0,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '18',
    name: 'Pediasure',
    slug: 'pediasure',
    brandName: 'Abbott',
    categorySlug: 'supplement',
    mrp: 980,
    salePrice: 875,
    discountPercent: 11,
    reviewCount: 59,
    rating: 4.7,
    isRxRequired: false,
    isFlashSale: false,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '24 HRS',
    cashback: 14,
    stockLeft: 6,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '19',
    name: 'Blackmores',
    slug: 'blackmores',
    brandName: 'Blackmores',
    categorySlug: 'supplement',
    mrp: 1500,
    salePrice: 1290,
    discountPercent: 14,
    reviewCount: 48,
    rating: 4.6,
    isRxRequired: false,
    isFlashSale: false,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '24 HRS',
    cashback: 21,
    stockLeft: 12,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '20',
    name: 'Herbal Cough',
    slug: 'herbal-cough',
    brandName: 'Hamdard',
    categorySlug: 'herbal',
    mrp: 120,
    salePrice: 95,
    discountPercent: 21,
    reviewCount: 34,
    rating: 4.1,
    isRxRequired: false,
    isFlashSale: true,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '12-24 HRS',
    cashback: 3,
    stockLeft: 15,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '21',
    name: 'Homeo Arsenicum',
    slug: 'homeo-arsenicum',
    brandName: 'SBL',
    categorySlug: 'homeopathy',
    mrp: 95,
    salePrice: 80,
    discountPercent: 16,
    reviewCount: 13,
    rating: 4.0,
    isRxRequired: false,
    isFlashSale: false,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '24 HRS',
    cashback: 2,
    stockLeft: 12,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
  const MockProduct(
    id: '22',
    name: 'Pet Calcium',
    slug: 'pet-calcium',
    brandName: 'VetPlus',
    categorySlug: 'pet-care',
    mrp: 650,
    salePrice: 560,
    discountPercent: 14,
    reviewCount: 11,
    rating: 4.4,
    isRxRequired: false,
    isFlashSale: false,
    inStock: true,
    imageUrl: '',
    deliveryBadge: '24 HRS',
    cashback: 9,
    stockLeft: 10,
    description: _defaultDesc,
    howToUse: _defaultUse,
    sideEffects: _defaultEffects,
    storage: _defaultStorage,
  ),
];

final List<MockProduct> flashSaleProducts = mockMedicines
    .where((p) => p.isFlashSale)
    .toList();
